version: '3'

services:
  frontend:
    build: './src/frontend'
    volumes:
      - './src/frontend/html:/usr/share/nginx/html'
    ports:
      - '8080:80'
  backend:
    build: './src/backend'
    volumes:
      - './src/backend:/app'
    ports:
      - '8000:80'
