name: Cloudflare deploy

on:
  workflow_dispatch:
  schedule:
    - cron: '15 15 * * *'
  push:
    branches: 
      - 'main'

jobs:
  wrangler:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Cloudflare configuration
        run: echo "CLOUDFLARE_API_TOKEN=${CLOUDFLARE_API_TOKEN}" > ./src/backend/.env
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}

      - name: Cloudflare deploy
        run: cd ./src/backend/ && npx wrangler deploy
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
